# Generated by Django 3.2.7 on 2021-09-08 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-z]+$', 'brand must be only lower alpha characters')], verbose_name='Бренд')),
                ('year', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2021)])),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_park.autoparkmodel')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'db_table': 'cars',
            },
        ),
    ]
