# Generated by Django 3.2.7 on 2021-09-03 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210903_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-z]$', 'brand must be only lower alpha characters')], verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
