# Generated by Django 3.2.7 on 2021-09-06 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210903_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-z]+$', 'brand must be only lower alpha characters')], verbose_name='Бренд'),
        ),
    ]
