# Generated by Django 3.2.7 on 2021-09-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_park', '0001_initial'),
        ('car', '0004_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='auto_park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_park.autoparkmodel'),
            preserve_default=False,
        ),
    ]
