# Generated by Django 3.2.7 on 2021-09-17 18:12

from django.db import migrations, models
import utils.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=utils.file_utils.FileUtils.avatar_upload_to),
        ),
    ]
